export const insights = [
  {
    id: 'claude-design',
    category: 'AI',
    title: 'Introducing Claude Design by Anthropic Labs',
    variant: 'fire',
    image: '/images/claudedesign.jpg',
    author: { name: 'Anthropic', role: 'anthropic.com' },
    date: 'Apr 17, 2026',
    href: 'https://www.anthropic.com/news/claude-design-anthropic-labs',
    tags: ['Product', 'Announcements'],
    body: [],
  },
  {
    id: 'planout-v2-launch',
    category: 'Events',
    title: 'Asbir Tech at the PlanOut V2 App Launch',
    variant: 'ember',
    image: '/images/asbirtecharticleimg2.jpg',
    author: { name: 'Asbir Tech', role: 'asbirtech.com' },
    date: 'Apr 11, 2026',
    tags: ['Events', 'Community'],
    href: 'https://www.facebook.com/share/p/1GHUNS7nvG/',
    body: [],
  },
  {
    id: 'openai-attack',
    category: 'Security',
    title: "Man Who Attacked OpenAI CEO's Home Had List of AI Executives",
    variant: 'gold',
    image: '/images/openai.jpeg',
    author: { name: 'New York Times', role: 'nytimes.com' },
    date: 'Apr 13, 2026',
    tags: ['Security', 'AI'],
    href: 'https://www.nytimes.com/2026/04/13/technology/man-who-attacked-openai-ceos-home-had-list-of-other-ai-executives.html',
    body: [],
  },
  {
    id: 'cloud-infrastructure-2026',
    category: 'Cloud',
    title: 'The State of Cloud Infrastructure in 2026',
    variant: 'ember',
    image: '/images/amazon.jpeg',
    author: { name: 'Cloud Security Alliance', role: 'csa.org' },
    date: 'Apr 10, 2026',
    tags: ['Cloud', 'Infrastructure'],
    href: 'https://www.infoworld.com/article/3956089/cloud-computing-trends-2026.html',
    body: [],
  },
  {
    id: 'open-source-ai',
    category: 'AI',
    title: 'How Open Source Is Winning the AI Race',
    variant: 'fire',
    image: 'https://cdn.prod.website-files.com/6720ed07d56bdfa402a08045/6720ed07d56bdfa402a084dd_Open_Source_Software_Bitcoin_Wallet_bp.webp',
    author: { name: 'Wired', role: 'wired.com' },
    date: 'Apr 8, 2026',
    tags: ['AI', 'Open Source'],
    href: 'https://www.wired.com/story/open-source-ai-is-winning/',
    body: [],
  },
  {
    id: 'react-19',
    category: 'Development',
    title: "What's New in React 19: Server Components, Actions & More",
    variant: 'gold',
    image: 'https://miro.medium.com/v2/resize:fit:720/format:webp/1*nBSqw2hm67ddA86iR1xLpw.png',
    author: { name: 'Vercel Blog', role: 'vercel.com' },
    date: 'Apr 2, 2026',
    tags: ['React', 'Frontend'],
    href: 'https://react.dev/blog/2024/12/05/react-19',
    body: [],
  },
  {
    id: 'philippines-tech-2026',
    category: 'Industry',
    title: "DeepSeek V4 may launch this month, test interface suggests Vision and Expert modes",
    variant: 'ember',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEFefPcyGkRdyLe1uMLJZC3xmfr-TPmcqGbg&s',
    author: { name: 'Tech Node', role: 'technode.com' },
    date: 'Mar 28, 2026',
    tags: ['Industry', 'Southeast Asia'],
    href: 'https://technode.com/2024/09/24/philippines-tech-ecosystem/',
    body: [],
  },
  {
    id: 'llm-agents-production',
    category: 'AI',
    title: 'Running LLM Agents in Production: What Nobody Tells You',
    variant: 'fire',
    image: 'https://i.ytimg.com/vi/D7_ipDqhtwk/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAjxSsC-46kVjASnhknaOy50C1T6Q',
    author: { name: 'Anthropic', role: 'asbirtech.com' },  
    date: 'Mar 20, 2026',
    tags: ['AI', 'Engineering'],
    href: 'https://www.anthropic.com/engineering/building-effective-agents',
    body: [],
  },
  {
    id: 'mobile-first-2026',
    category: 'Design',
    title: 'Mobile-First Is Dead. Long Live Mobile-Only.',
    variant: 'gold',
    image: 'https://media.licdn.com/dms/image/v2/D4E12AQEqYXzuosZaGg/article-cover_image-shrink_720_1280/B4EZedW9nsGcAI-/0/1750691734841?e=2147483647&v=beta&t=Rgc8QsFElMc8w5U2YdBk63_MhCKHzvTcjUMjN-2mUqA',
    author: { name: 'Smashing Magazine', role: 'smashingmagazine.com' },
    date: 'Mar 15, 2026',
    tags: ['Design', 'UX'],
    href: 'https://www.smashingmagazine.com/2024/01/mobile-ux-design-patterns-2024/',
    body: [],
  },
]
