export const insights = [
  {
    id: 'claude-design',
    category: 'AI',
    title: 'Introducing Claude Design by Anthropic Labs',
    variant: 'fire',
    image: '/images/claudedesign.jpg',
    author: { name: 'Anthropic', role: 'anthropic.com' },
    date: 'Apr 17, 2026',
    href: 'https://www.anthropic.com/news/claude-design-anthropic-labs',
    tags: ['Product', 'Announcements'],
    body: [],
  },
  {
    id: 'planout-v2-launch',
    category: 'Events',
    title: 'Asbir Tech at the PlanOut V2 App Launch',
    variant: 'ember',
    image: '/images/asbirtecharticleimg2.jpg',
    author: { name: 'Asbir Tech', role: 'asbirtech.com' },
    date: 'Apr 11, 2026',
    tags: ['Events', 'Community'],
    href: 'https://www.facebook.com/share/p/1GHUNS7nvG/',
    body: [],
  },
  {
    id: 'openai-attack',
    category: 'Security',
    title: "Man Who Attacked OpenAI CEO's Home Had List of AI Executives",
    variant: 'gold',
    image: '/images/openai.jpeg',
    author: { name: 'New York Times', role: 'nytimes.com' },
    date: 'Apr 13, 2026',
    tags: ['Security', 'AI'],
    href: 'https://www.nytimes.com/2026/04/13/technology/man-who-attacked-openai-ceos-home-had-list-of-other-ai-executives.html',
    body: [],
  },
  {
    id: 'cloud-infrastructure-2026',
    category: 'Cloud',
    title: 'The State of Cloud Infrastructure in 2026',
    variant: 'ember',
    image: '/images/amazon.jpeg',
    author: { name: 'Asbir Tech', role: 'asbirtech.com' },
    date: 'Apr 10, 2026',
    tags: ['Cloud', 'Infrastructure'],
    href: '#',
    body: [],
  },
]
